server:
  port: 8080

swift:
  jwt:
    location: classpath:swiftshop.jks # 秘钥地址
    alias: swiftshop # 秘钥别名
    password: 123456 # 秘钥文件密码
    tokenTTL: 30m # 登录有效期
  auth:
    excludePaths: # 无需登录校验的路径
      - /search/**
      - /users/login
      - /items/**
